[build]
  publish = "."

# API redirect for Netlify functions (REQUIRED!)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Specific redirects for your pages
[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/post/*"
  to = "/post.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Catch-all redirect (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false