[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Only redirect unmatched routes (not existing files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false